[project]
name = "black-inter-servers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.4",
    "gevent>=24.11.1",
    "gunicorn>=23.0.0",
    "python-decouple>=3.8",
]
